language: python
python:
  - "3.6"

notifications:
  email: false

services:
  - mysql
  - redis-server
  - docker

before_install:
  - sudo mysql -e 'CREATE DATABASE test DEFAULT CHARSET utf8 COLLATE utf8_general_ci;'
  - sudo mysql -e 'CREATE DATABASE netease DEFAULT CHARSET utf8 COLLATE utf8_general_ci;'

cache:
  directories:
    - $HOME/.pip-cache/

install:
  - cd webapp && pip install -r requirements.txt
  - pip install coverage
  - pip install codecov

script:
  - cd tests && coverage run -m unittest discover
  - docker-compose build
  - docker-compose up -d
  - docker-compose logs



after_success:
  - codecov
  - docker-compose logs
  - sleep 3m && curl 127.0.0.1/v1/employees?page=1&per_page=5
  - docker-compose logs
