language: python
python:
  - "3.6"

notifications:
  email: false

services:
  - mysql
  - redis
  - docker

before_install:
  - sudo mysql -e 'CREATE DATABASE test DEFAULT CHARSET utf8 COLLATE utf8_general_ci;'
  - sudo mysql -e 'CREATE DATABASE netease DEFAULT CHARSET utf8 COLLATE utf8_general_ci;'
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

cache:
  pip: true
  directories:
      - $HOME/docker

before_cache:
  - mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

install:
  - cd webapp && pip install -r requirements.txt
  - pip install codecov

script:
  - cd tests && coverage run -m unittest discover
  - docker-compose up --build -d


after_success:
  - codecov
  - docker-compose logs
  - curl http://127.0.0.1/v1/employees\?page\=1\&per_page\=5

