language: python
python:
  - "3.6"

notifications:
  email: false

services:
  - mysql

before_install:
  - sudo mysql -e 'CREATE DATABASE test DEFAULT CHARSET utf8 COLLATE utf8_general_ci;'
  - sudo mysql -e 'CREATE DATABASE netease DEFAULT CHARSET utf8 COLLATE utf8_general_ci;'

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codecov

script:
  - cd test && coverage run test_curd.py

after_success:
  - codecov