"""update table employee cloumn name

Revision ID: fa2069a8237e
Revises: e17af90a5441
Create Date: 2020-02-08 17:55:27.055464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa2069a8237e'
down_revision = 'e17af90a5441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='db_employee')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'db_employee', ['name'], unique=True)
    # ### end Alembic commands ###
